create table if not exists users (
    id bigint generated by default as identity not null,
    login varchar(25) not null,
    password varchar(25) not null,
    first_name varchar(40) not null,
    last_name varchar(40) not null,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

create table if not exists roles (
    id bigint generated by default as identity not null,
    user_id bigint not null,
    role varchar(10) not null,
    CONSTRAINT pk_role PRIMARY KEY (id),
    CONSTRAINT fk_role_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

