create table if not exists users (
    id bigint generated by default as identity not null,
    login varchar(25) not null,
    password varchar(25) not null,
    first_name varchar(40) not null,
    last_name varchar(40) not null,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

create table if not exists roles (
    id bigint generated by default as identity not null,
    user_id bigint not null,
    role varchar(10) not null,
    CONSTRAINT pk_role PRIMARY KEY (id),
    CONSTRAINT fk_role_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

insert into users (login, password, first_name, last_name) values ('andrey', '1234', 'andrey', 'k');
insert into users (login, password, first_name, last_name) values ('anton', '1234', 'anton', 'k');
insert into roles (user_id, role) values (1, 'admin');
insert into roles (user_id, role) values (2, 'user');

